# Jekyll
source: source
destination: public
plugins: plugins
markdown: kramdown
paginate: 5

# ====== wido.me ======
# octopress
url: https://wido.me
title: "{ wido.me }"
permalink: "/:categories/:title/"
simple_search: http://google.com/search
subscribe_rss: /atom.xml

excerpt_link: "阅读全部 &rarr;"
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

disqus_short_name: wido
disqus_show_comment_count: false

google_analytics_tracking_id: UA-27596203-1


# plugins
bundles:
  Develop:
    - any: ruby rails server linux java ubuntu
  iOS:
    - any: ios cydia iphone ipad
  Mac: 
    - any: mac lion
    - not: ruby rails
  GFW:
    - any: gfw

